# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist =
    fmt
    py{314,313,312,311,310,39}
skip_missing_interpreters = true

[tool:pytest]
testpaths = tests
addopts =
    --cov-report=term-missing

[testenv]
description = run the unit tests under {basepython}
setenv =
    COVERAGE_FILE = {toxworkdir}/.coverage.{envname}
deps =
    coverage >= 7.0
    pytest >= 7.0.0
    pytest-cov >= 4.0.0
    pytest-mock >= 3.0.0
    pytest-xdist >= 3.0.0
    requests ~= 2.32
commands = pytest --cov {posargs:-n auto}
# compilation flags can be useful when prebuilt wheels cannot be used, e.g.
# PyPy 2 needs to compile the `cryptography` module. On macOS this can be done
# by passing the following flags:
# LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
# CFLAGS="-I$(brew --prefix openssl@1.1)/include"
#passenv = LDFLAGS CFLAGS

[testenv:fmt]
description = run code formatting using black
basepython = python
deps = black==25.9.0
commands = black . {posargs}
skip_install = true
